name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: cargo test and fmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test_rust
    steps:
      - uses: actions/checkout@v4
      - id: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: ls -la ~/.cargo/bin
      - id: cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: test_rust
      - run: ls -la ~/.cargo/bin
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest@0.9.75
      # - run: cargo test --all-features
      - run: ls -la ~/.cargo/bin
      - run: cargo nextest run --all-features
      - run: cargo fmt --all --check
      - run: echo "${{steps.toolchain.outputs.cachekey}} ${{steps.toolchain.outputs.name}}"
      - run: echo "${{steps.cache.outputs.cache-hit}}"
